# Generated by Django 4.2.4 on 2023-08-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagruti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
    ]
