# Generated by Django 4.2.4 on 2023-08-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagruti', '0002_candidate_country_candidate_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='country',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
    ]
