# Generated by Django 4.2.4 on 2023-08-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jagruti', '0005_jobdeatils'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdeatils',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jagruti.company'),
        ),
    ]
