# Generated by Django 4.2.4 on 2023-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagruti', '0007_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
